In [1]:
import pandas as pd
import yfinance as yf 

import warnings
warnings.filterwarnings("ignore")

In [2]:
lista_ativos = list(pd.read_csv('https://raw.githubusercontent.com/Lessalc/Long-Short/main/ativos.txt'))
char_excluido = -3

In [22]:
dados = yf.download(tickers = lista_ativos, period='2y', interval='1d', auto_adjust=True)
dados = dados['Close']
dados = dados.loc[dados['^BVSP'].notna(), :]
dados.dropna(axis=1, how='any', inplace=True)
dados.dropna(axis=0, how='all', inplace=True)
dados.drop(columns=['^BVSP'], inplace=True)

[*********************100%***********************]  83 of 83 completed

1 Failed download:
- UNNAMED: 82: No data found, symbol may be delisted

In [23]:
dados = dados.iloc[-250:]
dados.head()

,ABEV3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,BEEF3.SA,BPAC11.SA,BRAP4.SA,...,SUZB3.SA,TAEE11.SA,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VIVT3.SA,VVAR3.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-30,17.782818,59.709999,47.190556,47.870525,28.024065,29.574884,32.761429,11.086839,72.870789,36.127945,...,40.509998,28.091440,24.030035,25.634651,9.679872,49.433552,48.189663,14.65,40.642761,51.322544
2020-01-31,17.307703,59.259998,46.610348,46.659340,27.714647,29.079762,31.997826,11.581961,73.265373,35.494965,...,39.669998,27.983568,24.674582,24.943426,9.541162,48.252907,47.806263,14.00,39.095219,51.734772
2020-02-03,17.055603,60.130001,48.438011,46.890041,27.917980,29.265430,32.135826,11.950874,74.459007,36.137539,...,39.500000,28.082451,25.920706,25.042173,9.610517,48.867226,48.436131,14.49,40.345154,53.854809
2020-02-04,17.113779,60.799999,48.312298,46.380577,28.021688,29.282213,31.694225,11.688751,73.975632,37.019875,...,38.889999,28.064472,25.781879,24.815054,9.699686,50.172657,48.162270,14.95,40.196354,55.552799
2020-02-05,16.725931,61.270000,47.722412,48.447281,28.534712,29.848398,31.859825,11.747002,77.359238,37.269234,...,38.400002,28.109423,25.864513,25.091545,10.175259,50.863770,47.851894,15.14,41.039566,54.473152

In [24]:
colunas = ['Data']+list(dados.columns)
for i in range(1,len(colunas)):
    colunas[i] = colunas[i][:char_excluido]
dados.reset_index(inplace=True)
dados.columns = colunas

In [25]:
print(dados.shape)
dados.head()

(250, 80)

,Data,ABEV3,AZUL4,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,BPAC11,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VIVT3,VVAR3,WEGE3,YDUQ3
0,2020-01-30,17.782818,59.709999,47.190556,47.870525,28.024065,29.574884,32.761429,11.086839,72.870789,...,40.509998,28.091440,24.030035,25.634651,9.679872,49.433552,48.189663,14.65,40.642761,51.322544
1,2020-01-31,17.307703,59.259998,46.610348,46.659340,27.714647,29.079762,31.997826,11.581961,73.265373,...,39.669998,27.983568,24.674582,24.943426,9.541162,48.252907,47.806263,14.00,39.095219,51.734772
2,2020-02-03,17.055603,60.130001,48.438011,46.890041,27.917980,29.265430,32.135826,11.950874,74.459007,...,39.500000,28.082451,25.920706,25.042173,9.610517,48.867226,48.436131,14.49,40.345154,53.854809
3,2020-02-04,17.113779,60.799999,48.312298,46.380577,28.021688,29.282213,31.694225,11.688751,73.975632,...,38.889999,28.064472,25.781879,24.815054,9.699686,50.172657,48.162270,14.95,40.196354,55.552799
4,2020-02-05,16.725931,61.270000,47.722412,48.447281,28.534712,29.848398,31.859825,11.747002,77.359238,...,38.400002,28.109423,25.864513,25.091545,10.175259,50.863770,47.851894,15.14,41.039566,54.473152

In [27]:
dados.to_csv('BD_Precos.csv', index=False, header=True)